add conditional failure

diff --git a/.github/workflows/code-quality.yml b/.github/workflows/code-quality.yml
--- a/.github/workflows/code-quality.yml
+++ b/.github/workflows/code-quality.yml
@@ -35,7 +35,11 @@ jobs:
     
   code-quality-result:
     runs-on: ubuntu-latest
+    if: always()
     needs: [ cas-code-quality-check, plugin-code-quality-check ]
     steps:
-      - name: Success
-        run: echo "All code quality checks passed!"
+      - name: Failure
+        if: ${{ contains(needs.*.result, 'failure') }}
+        run: | 
+          echo "Code quality check failed!"
+          exit 1
diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -26,8 +26,12 @@ jobs:
   
   test-result:
     runs-on: ubuntu-latest
+    if: always()
     needs: [ test-sympy-client ]
     steps:
-      - name: Success
-        run: echo "All tests passed!"
+      - name: Failure
+        if: ${{ contains(needs.*.result, 'failure') }}
+        run: | 
+          echo "Test failed!"
+          exit 1
   
